[package]
name = "signaller"
version = "0.1.0"
authors = ["Luo <gnulinux@126.com>"]

[dependencies]
# time     = "0.1.35"
ws       = "0.5.0"
# log      = "0.3.6"
bson     = "0.2.0"
# env_logger      = "0.3.3"
rustc-serialize = "0.3"